version: "3"
services:
  oem-ui:
    image: darknightcoder/tess-oem-ui:latest
    ports:
      - "4001:80"
    deploy: 
      replicas: 2     
  user-ui: 
    image: darknightcoder/tess-user-ui:latest
    ports:
      - "4002:80"
    deploy: 
      replicas: 2          
  mongo:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"
    networks: 
      - tesseract-main
    deploy: 
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  geth-service:
     image: darknightcoder/eth-poa:latest
     ports: 
       - "8545:8545"
     environment:
       - ALLOC_WEI=4C485837A2FB712D800000
       - ACCOUNTS_TO_CREATE=5
     networks: 
       - tesseract-eth
     deploy: 
       replicas: 2 
  contract-deployer:
     image: darknightcoder/tess-contract-deployer:latest
     command: bash -c "sleep 10s && node contractSetup.js"
     networks: 
      - tesseract-main
      - tesseract-eth     
  car-service:
    image: darknightcoder/tess-cs:latest
    ports: 
      - "3002:3002"
    networks: 
      - tesseract-main
  booking-service:
    image: darknightcoder/tess-bs:latest
    ports: 
      - "3030:3030"
    networks: 
      - tesseract-main
  main-service: 
    image: darknightcoder/tess-main:latest-1
    ports: 
      - "80:8081"
    command: bash -c "while ping -c1 contract-deployer &>/dev/null; do sleep 1; done && echo 'alright contract-deployer is badass lets start server' && forever /main-service/server.js"
    networks: 
      - tesseract-main
      - tesseract-eth            
 
networks:
  tesseract-main:
  tesseract-eth:
