version: "3"
services:
  oem-ui:
    image: darknightcoder/tess-oem-ui:latest
    ports:
      - "3002:80"
  user-ui: 
    image: darknightcoder/tess-user-ui:latest
    ports:
      - "80:80"       
  mongo:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"
    networks: 
      - tesseract
  geth-service:
     image: darknightocoder/eth-poa:latest
     ports: 
       - "8545:8545"
     environment:
       - EXTERNAL_ALLOCS=0x9d8393dd96eeb9c9bca5c84e186d8b5eca96f595
       - ALLOC_WEI=4C485837A2FB712D800000
       - ACCOUNTS_TO_CREATE=5

     networks: 
       - tesseract
  contract-deployer:
     image: darknightcoder/tess-contract-deployer:latest
     networks: 
      - tesseract
     depends_on:
      - mongo
      - geth-service     
  car-service:
    image: darknightcoder/tess-cs:latest
    ports: 
      - "3002:3002"
    networks: 
      - tesseract
  booking-service:
    image: darknightcoder/tess-bs:latest
    ports: 
      - "3030:3030"
    networks: 
      - tesseract
  main-service: 
    image: darknightcoder/tess-main:latest-1
    command: forever /main-service/server.js
    ports: 
      - "80:8081"
    networks: 
      - tesseract            
 
networks:
  tesseract:
